# Generated by Django 2.2.5 on 2019-09-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_int', models.IntegerField(default=0, verbose_name='Sample IntegerField')),
                ('sample_char', models.CharField(max_length=200, verbose_name='Sample CharField')),
                ('sample_text', models.TextField(default='', verbose_name='Sample TextField')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
